set -g mode-style "fg=#1e1e2e,bg=#f38ba8"
set -g message-style "fg=#1e1e2e,bg=#eba0ac"
set -g message-command-style "fg=#1e1e2e,bg=#f38ba8"

# Pane borders
set -g pane-border-style "fg=#313244"          # Surface0
set -g pane-active-border-style "fg=#cdd6f4"   # Text

# Status bar
set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#6c7086,bg=default"
set -g status-bg default

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

# Left status
set -g status-left "#[fg=#1e1e2e,bg=#cdd6f4,bold] #S:#I.#P #[fg=#cdd6f4,bg=#7f849c,nobold,nounderscore,noitalics]#[fg=#1e1e2e,bg=#7f849c,bold] #(whoami) #[fg=#7f849c,bg=#1e1e2e]"

# Right status
set -g status-right "#[fg=#6c7086,bg=#1e1e2e,nobold,nounderscore,noitalics]#[fg=#7f849c,bg=#6c7086]#[fg=#9399b2,bg=#6c7086,nobold,nounderscore,noitalics]#[fg=#7f849c,bg=#9399b2]#[fg=#9399b2,bg=#9399b2,nobold,nounderscore,noitalics]#[fg=#1e1e2e,bg=#9399b2,bold] #h "

# Windows
setw -g window-status-activity-style "underscore,fg=#bac2de,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#bac2de,bg=default"

setw -g window-status-format '#[fg=#1e1e2e,bg=default]#[default] #I  #{b:pane_current_path}'

# Active window
setw -g window-status-current-format '#[fg=#1e1e2e,bg=#cdd6f4]#[fg=#1e1e2e,bg=#cdd6f4] #I #[fg=#cdd6f4,bg=#89b4fa] #[fg=#1e1e2e,bg=#89b4fa]#{b:pane_current_path} #[fg=#89b4fa,bg=#1e1e2e,nobold]'
